version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/app
    tty: true
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: .docker/app
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: 'Asia/Tokyo'
    volumes:
      - .:/app
    expose:
      - 9000
    tty: true
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    container_name: db
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'laravel_development'
    volumes:
      - database:/var/lib/postgresql/data
      - ./.docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  mail:
    image: schickling/mailcatcher
    container_name: mail
    ports:
      - 1080:1080
    expose:
      - 1025

volumes:
  database:
